#!/bin/bash
export DISPLAY=localhost:0.0
case $1 in
start)  
pid=$(($$ + 1))
echo $pid > /tmp/main_driver.pid;
exec 2>&1 nohup node main.js >/mnt/main_sfs.out & \
1>/tmp/main_driver.out 
;;
stop)  
kill `cat /tmp/main_driver.pid` ;;
*)  
echo "usage: main_driver {start|stop}" ;;
esac
