// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oplogmsg.proto

package mobile.context.msg;

public final class OpLogDumpMessageProto {
  private OpLogDumpMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OpLogDumpMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string client_id = 1;
    boolean hasClientId();
    String getClientId();
    
    // repeated .mobile.context.msg.Operation oplog = 2;
    java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> 
        getOplogList();
    mobile.context.msg.OpLogDumpMessageProto.Operation getOplog(int index);
    int getOplogCount();
    java.util.List<? extends mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
        getOplogOrBuilderList();
    mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder getOplogOrBuilder(
        int index);
    
    // required .mobile.context.msg.OpLogDumpMessage.Type type = 3;
    boolean hasType();
    mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type getType();
  }
  public static final class OpLogDumpMessage extends
      com.google.protobuf.GeneratedMessage
      implements OpLogDumpMessageOrBuilder {
    // Use OpLogDumpMessage.newBuilder() to construct.
    private OpLogDumpMessage(Builder builder) {
      super(builder);
    }
    private OpLogDumpMessage(boolean noInit) {}
    
    private static final OpLogDumpMessage defaultInstance;
    public static OpLogDumpMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public OpLogDumpMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogDumpMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogDumpMessage_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      DUMP(0, 1),
      DUMP_REPLY(1, 2),
      ;
      
      public static final int DUMP_VALUE = 1;
      public static final int DUMP_REPLY_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return DUMP;
          case 2: return DUMP_REPLY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        DUMP, DUMP_REPLY, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:mobile.context.msg.OpLogDumpMessage.Type)
    }
    
    private int bitField0_;
    // optional string client_id = 1;
    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private java.lang.Object clientId_;
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          clientId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .mobile.context.msg.Operation oplog = 2;
    public static final int OPLOG_FIELD_NUMBER = 2;
    private java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> oplog_;
    public java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> getOplogList() {
      return oplog_;
    }
    public java.util.List<? extends mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
        getOplogOrBuilderList() {
      return oplog_;
    }
    public int getOplogCount() {
      return oplog_.size();
    }
    public mobile.context.msg.OpLogDumpMessageProto.Operation getOplog(int index) {
      return oplog_.get(index);
    }
    public mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder getOplogOrBuilder(
        int index) {
      return oplog_.get(index);
    }
    
    // required .mobile.context.msg.OpLogDumpMessage.Type type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type getType() {
      return type_;
    }
    
    private void initFields() {
      clientId_ = "";
      oplog_ = java.util.Collections.emptyList();
      type_ = mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type.DUMP;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOplogCount(); i++) {
        if (!getOplog(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClientIdBytes());
      }
      for (int i = 0; i < oplog_.size(); i++) {
        output.writeMessage(2, oplog_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(3, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientIdBytes());
      }
      for (int i = 0; i < oplog_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, oplog_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogDumpMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogDumpMessage_fieldAccessorTable;
      }
      
      // Construct using mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOplogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        clientId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (oplogBuilder_ == null) {
          oplog_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          oplogBuilder_.clear();
        }
        type_ = mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type.DUMP;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.getDescriptor();
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage getDefaultInstanceForType() {
        return mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.getDefaultInstance();
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage build() {
        mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage buildPartial() {
        mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage result = new mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientId_ = clientId_;
        if (oplogBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            oplog_ = java.util.Collections.unmodifiableList(oplog_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.oplog_ = oplog_;
        } else {
          result.oplog_ = oplogBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage) {
          return mergeFrom((mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage other) {
        if (other == mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.getDefaultInstance()) return this;
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (oplogBuilder_ == null) {
          if (!other.oplog_.isEmpty()) {
            if (oplog_.isEmpty()) {
              oplog_ = other.oplog_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOplogIsMutable();
              oplog_.addAll(other.oplog_);
            }
            onChanged();
          }
        } else {
          if (!other.oplog_.isEmpty()) {
            if (oplogBuilder_.isEmpty()) {
              oplogBuilder_.dispose();
              oplogBuilder_ = null;
              oplog_ = other.oplog_;
              bitField0_ = (bitField0_ & ~0x00000002);
              oplogBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOplogFieldBuilder() : null;
            } else {
              oplogBuilder_.addAllMessages(other.oplog_);
            }
          }
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getOplogCount(); i++) {
          if (!getOplog(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              clientId_ = input.readBytes();
              break;
            }
            case 18: {
              mobile.context.msg.OpLogDumpMessageProto.Operation.Builder subBuilder = mobile.context.msg.OpLogDumpMessageProto.Operation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOplog(subBuilder.buildPartial());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type value = mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string client_id = 1;
      private java.lang.Object clientId_ = "";
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClientId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      void setClientId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
      }
      
      // repeated .mobile.context.msg.Operation oplog = 2;
      private java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> oplog_ =
        java.util.Collections.emptyList();
      private void ensureOplogIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          oplog_ = new java.util.ArrayList<mobile.context.msg.OpLogDumpMessageProto.Operation>(oplog_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          mobile.context.msg.OpLogDumpMessageProto.Operation, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder, mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> oplogBuilder_;
      
      public java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> getOplogList() {
        if (oplogBuilder_ == null) {
          return java.util.Collections.unmodifiableList(oplog_);
        } else {
          return oplogBuilder_.getMessageList();
        }
      }
      public int getOplogCount() {
        if (oplogBuilder_ == null) {
          return oplog_.size();
        } else {
          return oplogBuilder_.getCount();
        }
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation getOplog(int index) {
        if (oplogBuilder_ == null) {
          return oplog_.get(index);
        } else {
          return oplogBuilder_.getMessage(index);
        }
      }
      public Builder setOplog(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation value) {
        if (oplogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOplogIsMutable();
          oplog_.set(index, value);
          onChanged();
        } else {
          oplogBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOplog(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder builderForValue) {
        if (oplogBuilder_ == null) {
          ensureOplogIsMutable();
          oplog_.set(index, builderForValue.build());
          onChanged();
        } else {
          oplogBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOplog(mobile.context.msg.OpLogDumpMessageProto.Operation value) {
        if (oplogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOplogIsMutable();
          oplog_.add(value);
          onChanged();
        } else {
          oplogBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOplog(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation value) {
        if (oplogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOplogIsMutable();
          oplog_.add(index, value);
          onChanged();
        } else {
          oplogBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOplog(
          mobile.context.msg.OpLogDumpMessageProto.Operation.Builder builderForValue) {
        if (oplogBuilder_ == null) {
          ensureOplogIsMutable();
          oplog_.add(builderForValue.build());
          onChanged();
        } else {
          oplogBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOplog(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder builderForValue) {
        if (oplogBuilder_ == null) {
          ensureOplogIsMutable();
          oplog_.add(index, builderForValue.build());
          onChanged();
        } else {
          oplogBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOplog(
          java.lang.Iterable<? extends mobile.context.msg.OpLogDumpMessageProto.Operation> values) {
        if (oplogBuilder_ == null) {
          ensureOplogIsMutable();
          super.addAll(values, oplog_);
          onChanged();
        } else {
          oplogBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOplog() {
        if (oplogBuilder_ == null) {
          oplog_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          oplogBuilder_.clear();
        }
        return this;
      }
      public Builder removeOplog(int index) {
        if (oplogBuilder_ == null) {
          ensureOplogIsMutable();
          oplog_.remove(index);
          onChanged();
        } else {
          oplogBuilder_.remove(index);
        }
        return this;
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Builder getOplogBuilder(
          int index) {
        return getOplogFieldBuilder().getBuilder(index);
      }
      public mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder getOplogOrBuilder(
          int index) {
        if (oplogBuilder_ == null) {
          return oplog_.get(index);  } else {
          return oplogBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
           getOplogOrBuilderList() {
        if (oplogBuilder_ != null) {
          return oplogBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(oplog_);
        }
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Builder addOplogBuilder() {
        return getOplogFieldBuilder().addBuilder(
            mobile.context.msg.OpLogDumpMessageProto.Operation.getDefaultInstance());
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Builder addOplogBuilder(
          int index) {
        return getOplogFieldBuilder().addBuilder(
            index, mobile.context.msg.OpLogDumpMessageProto.Operation.getDefaultInstance());
      }
      public java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation.Builder> 
           getOplogBuilderList() {
        return getOplogFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          mobile.context.msg.OpLogDumpMessageProto.Operation, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder, mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
          getOplogFieldBuilder() {
        if (oplogBuilder_ == null) {
          oplogBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              mobile.context.msg.OpLogDumpMessageProto.Operation, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder, mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder>(
                  oplog_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          oplog_ = null;
        }
        return oplogBuilder_;
      }
      
      // required .mobile.context.msg.OpLogDumpMessage.Type type = 3;
      private mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type type_ = mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type.DUMP;
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type getType() {
        return type_;
      }
      public Builder setType(mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Type.DUMP;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:mobile.context.msg.OpLogDumpMessage)
    }
    
    static {
      defaultInstance = new OpLogDumpMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mobile.context.msg.OpLogDumpMessage)
  }
  
  public interface OpLogEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // repeated .mobile.context.msg.Operation ops = 2;
    java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> 
        getOpsList();
    mobile.context.msg.OpLogDumpMessageProto.Operation getOps(int index);
    int getOpsCount();
    java.util.List<? extends mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
        getOpsOrBuilderList();
    mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder getOpsOrBuilder(
        int index);
    
    // required string objname = 3;
    boolean hasObjname();
    String getObjname();
  }
  public static final class OpLogEntry extends
      com.google.protobuf.GeneratedMessage
      implements OpLogEntryOrBuilder {
    // Use OpLogEntry.newBuilder() to construct.
    private OpLogEntry(Builder builder) {
      super(builder);
    }
    private OpLogEntry(boolean noInit) {}
    
    private static final OpLogEntry defaultInstance;
    public static OpLogEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public OpLogEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogEntry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // repeated .mobile.context.msg.Operation ops = 2;
    public static final int OPS_FIELD_NUMBER = 2;
    private java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> ops_;
    public java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> getOpsList() {
      return ops_;
    }
    public java.util.List<? extends mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
        getOpsOrBuilderList() {
      return ops_;
    }
    public int getOpsCount() {
      return ops_.size();
    }
    public mobile.context.msg.OpLogDumpMessageProto.Operation getOps(int index) {
      return ops_.get(index);
    }
    public mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder getOpsOrBuilder(
        int index) {
      return ops_.get(index);
    }
    
    // required string objname = 3;
    public static final int OBJNAME_FIELD_NUMBER = 3;
    private java.lang.Object objname_;
    public boolean hasObjname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getObjname() {
      java.lang.Object ref = objname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          objname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getObjnameBytes() {
      java.lang.Object ref = objname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        objname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      timestamp_ = 0L;
      ops_ = java.util.Collections.emptyList();
      objname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObjname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOpsCount(); i++) {
        if (!getOps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, timestamp_);
      }
      for (int i = 0; i < ops_.size(); i++) {
        output.writeMessage(2, ops_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getObjnameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      for (int i = 0; i < ops_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, ops_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getObjnameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.OpLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mobile.context.msg.OpLogDumpMessageProto.OpLogEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mobile.context.msg.OpLogDumpMessageProto.OpLogEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_OpLogEntry_fieldAccessorTable;
      }
      
      // Construct using mobile.context.msg.OpLogDumpMessageProto.OpLogEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOpsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (opsBuilder_ == null) {
          ops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          opsBuilder_.clear();
        }
        objname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobile.context.msg.OpLogDumpMessageProto.OpLogEntry.getDescriptor();
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.OpLogEntry getDefaultInstanceForType() {
        return mobile.context.msg.OpLogDumpMessageProto.OpLogEntry.getDefaultInstance();
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.OpLogEntry build() {
        mobile.context.msg.OpLogDumpMessageProto.OpLogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private mobile.context.msg.OpLogDumpMessageProto.OpLogEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        mobile.context.msg.OpLogDumpMessageProto.OpLogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.OpLogEntry buildPartial() {
        mobile.context.msg.OpLogDumpMessageProto.OpLogEntry result = new mobile.context.msg.OpLogDumpMessageProto.OpLogEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (opsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            ops_ = java.util.Collections.unmodifiableList(ops_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.ops_ = ops_;
        } else {
          result.ops_ = opsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.objname_ = objname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobile.context.msg.OpLogDumpMessageProto.OpLogEntry) {
          return mergeFrom((mobile.context.msg.OpLogDumpMessageProto.OpLogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(mobile.context.msg.OpLogDumpMessageProto.OpLogEntry other) {
        if (other == mobile.context.msg.OpLogDumpMessageProto.OpLogEntry.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (opsBuilder_ == null) {
          if (!other.ops_.isEmpty()) {
            if (ops_.isEmpty()) {
              ops_ = other.ops_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOpsIsMutable();
              ops_.addAll(other.ops_);
            }
            onChanged();
          }
        } else {
          if (!other.ops_.isEmpty()) {
            if (opsBuilder_.isEmpty()) {
              opsBuilder_.dispose();
              opsBuilder_ = null;
              ops_ = other.ops_;
              bitField0_ = (bitField0_ & ~0x00000002);
              opsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOpsFieldBuilder() : null;
            } else {
              opsBuilder_.addAllMessages(other.ops_);
            }
          }
        }
        if (other.hasObjname()) {
          setObjname(other.getObjname());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasObjname()) {
          
          return false;
        }
        for (int i = 0; i < getOpsCount(); i++) {
          if (!getOps(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
            case 18: {
              mobile.context.msg.OpLogDumpMessageProto.Operation.Builder subBuilder = mobile.context.msg.OpLogDumpMessageProto.Operation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOps(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              objname_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .mobile.context.msg.Operation ops = 2;
      private java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> ops_ =
        java.util.Collections.emptyList();
      private void ensureOpsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ops_ = new java.util.ArrayList<mobile.context.msg.OpLogDumpMessageProto.Operation>(ops_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          mobile.context.msg.OpLogDumpMessageProto.Operation, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder, mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> opsBuilder_;
      
      public java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation> getOpsList() {
        if (opsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ops_);
        } else {
          return opsBuilder_.getMessageList();
        }
      }
      public int getOpsCount() {
        if (opsBuilder_ == null) {
          return ops_.size();
        } else {
          return opsBuilder_.getCount();
        }
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation getOps(int index) {
        if (opsBuilder_ == null) {
          return ops_.get(index);
        } else {
          return opsBuilder_.getMessage(index);
        }
      }
      public Builder setOps(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation value) {
        if (opsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOpsIsMutable();
          ops_.set(index, value);
          onChanged();
        } else {
          opsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOps(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder builderForValue) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.set(index, builderForValue.build());
          onChanged();
        } else {
          opsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOps(mobile.context.msg.OpLogDumpMessageProto.Operation value) {
        if (opsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOpsIsMutable();
          ops_.add(value);
          onChanged();
        } else {
          opsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOps(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation value) {
        if (opsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOpsIsMutable();
          ops_.add(index, value);
          onChanged();
        } else {
          opsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOps(
          mobile.context.msg.OpLogDumpMessageProto.Operation.Builder builderForValue) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.add(builderForValue.build());
          onChanged();
        } else {
          opsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOps(
          int index, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder builderForValue) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.add(index, builderForValue.build());
          onChanged();
        } else {
          opsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOps(
          java.lang.Iterable<? extends mobile.context.msg.OpLogDumpMessageProto.Operation> values) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          super.addAll(values, ops_);
          onChanged();
        } else {
          opsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOps() {
        if (opsBuilder_ == null) {
          ops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          opsBuilder_.clear();
        }
        return this;
      }
      public Builder removeOps(int index) {
        if (opsBuilder_ == null) {
          ensureOpsIsMutable();
          ops_.remove(index);
          onChanged();
        } else {
          opsBuilder_.remove(index);
        }
        return this;
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Builder getOpsBuilder(
          int index) {
        return getOpsFieldBuilder().getBuilder(index);
      }
      public mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder getOpsOrBuilder(
          int index) {
        if (opsBuilder_ == null) {
          return ops_.get(index);  } else {
          return opsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
           getOpsOrBuilderList() {
        if (opsBuilder_ != null) {
          return opsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ops_);
        }
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Builder addOpsBuilder() {
        return getOpsFieldBuilder().addBuilder(
            mobile.context.msg.OpLogDumpMessageProto.Operation.getDefaultInstance());
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Builder addOpsBuilder(
          int index) {
        return getOpsFieldBuilder().addBuilder(
            index, mobile.context.msg.OpLogDumpMessageProto.Operation.getDefaultInstance());
      }
      public java.util.List<mobile.context.msg.OpLogDumpMessageProto.Operation.Builder> 
           getOpsBuilderList() {
        return getOpsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          mobile.context.msg.OpLogDumpMessageProto.Operation, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder, mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder> 
          getOpsFieldBuilder() {
        if (opsBuilder_ == null) {
          opsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              mobile.context.msg.OpLogDumpMessageProto.Operation, mobile.context.msg.OpLogDumpMessageProto.Operation.Builder, mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder>(
                  ops_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          ops_ = null;
        }
        return opsBuilder_;
      }
      
      // required string objname = 3;
      private java.lang.Object objname_ = "";
      public boolean hasObjname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getObjname() {
        java.lang.Object ref = objname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          objname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setObjname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        objname_ = value;
        onChanged();
        return this;
      }
      public Builder clearObjname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        objname_ = getDefaultInstance().getObjname();
        onChanged();
        return this;
      }
      void setObjname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        objname_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:mobile.context.msg.OpLogEntry)
    }
    
    static {
      defaultInstance = new OpLogEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mobile.context.msg.OpLogEntry)
  }
  
  public interface OperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .mobile.context.msg.Operation.Type type = 1 [default = GET];
    boolean hasType();
    mobile.context.msg.OpLogDumpMessageProto.Operation.Type getType();
    
    // optional bytes data = 2;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Operation extends
      com.google.protobuf.GeneratedMessage
      implements OperationOrBuilder {
    // Use Operation.newBuilder() to construct.
    private Operation(Builder builder) {
      super(builder);
    }
    private Operation(boolean noInit) {}
    
    private static final Operation defaultInstance;
    public static Operation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Operation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_Operation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_Operation_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      GET(0, 0),
      PUT(1, 1),
      POST(2, 2),
      DELETE(3, 3),
      MOVE(4, 4),
      GET_OK(5, 5),
      GET_FAIL(6, 6),
      PUT_OK(7, 7),
      PUT_FAIL(8, 8),
      POST_OK(9, 9),
      POST_FAIL(10, 10),
      DELETE_OK(11, 11),
      DELETE_FAIL(12, 12),
      ;
      
      public static final int GET_VALUE = 0;
      public static final int PUT_VALUE = 1;
      public static final int POST_VALUE = 2;
      public static final int DELETE_VALUE = 3;
      public static final int MOVE_VALUE = 4;
      public static final int GET_OK_VALUE = 5;
      public static final int GET_FAIL_VALUE = 6;
      public static final int PUT_OK_VALUE = 7;
      public static final int PUT_FAIL_VALUE = 8;
      public static final int POST_OK_VALUE = 9;
      public static final int POST_FAIL_VALUE = 10;
      public static final int DELETE_OK_VALUE = 11;
      public static final int DELETE_FAIL_VALUE = 12;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return PUT;
          case 2: return POST;
          case 3: return DELETE;
          case 4: return MOVE;
          case 5: return GET_OK;
          case 6: return GET_FAIL;
          case 7: return PUT_OK;
          case 8: return PUT_FAIL;
          case 9: return POST_OK;
          case 10: return POST_FAIL;
          case 11: return DELETE_OK;
          case 12: return DELETE_FAIL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mobile.context.msg.OpLogDumpMessageProto.Operation.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        GET, PUT, POST, DELETE, MOVE, GET_OK, GET_FAIL, PUT_OK, PUT_FAIL, POST_OK, POST_FAIL, DELETE_OK, DELETE_FAIL, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:mobile.context.msg.Operation.Type)
    }
    
    private int bitField0_;
    // required .mobile.context.msg.Operation.Type type = 1 [default = GET];
    public static final int TYPE_FIELD_NUMBER = 1;
    private mobile.context.msg.OpLogDumpMessageProto.Operation.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public mobile.context.msg.OpLogDumpMessageProto.Operation.Type getType() {
      return type_;
    }
    
    // optional bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      type_ = mobile.context.msg.OpLogDumpMessageProto.Operation.Type.GET;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mobile.context.msg.OpLogDumpMessageProto.Operation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mobile.context.msg.OpLogDumpMessageProto.Operation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mobile.context.msg.OpLogDumpMessageProto.OperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_Operation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mobile.context.msg.OpLogDumpMessageProto.internal_static_mobile_context_msg_Operation_fieldAccessorTable;
      }
      
      // Construct using mobile.context.msg.OpLogDumpMessageProto.Operation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = mobile.context.msg.OpLogDumpMessageProto.Operation.Type.GET;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mobile.context.msg.OpLogDumpMessageProto.Operation.getDescriptor();
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.Operation getDefaultInstanceForType() {
        return mobile.context.msg.OpLogDumpMessageProto.Operation.getDefaultInstance();
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.Operation build() {
        mobile.context.msg.OpLogDumpMessageProto.Operation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private mobile.context.msg.OpLogDumpMessageProto.Operation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        mobile.context.msg.OpLogDumpMessageProto.Operation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public mobile.context.msg.OpLogDumpMessageProto.Operation buildPartial() {
        mobile.context.msg.OpLogDumpMessageProto.Operation result = new mobile.context.msg.OpLogDumpMessageProto.Operation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mobile.context.msg.OpLogDumpMessageProto.Operation) {
          return mergeFrom((mobile.context.msg.OpLogDumpMessageProto.Operation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(mobile.context.msg.OpLogDumpMessageProto.Operation other) {
        if (other == mobile.context.msg.OpLogDumpMessageProto.Operation.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              mobile.context.msg.OpLogDumpMessageProto.Operation.Type value = mobile.context.msg.OpLogDumpMessageProto.Operation.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .mobile.context.msg.Operation.Type type = 1 [default = GET];
      private mobile.context.msg.OpLogDumpMessageProto.Operation.Type type_ = mobile.context.msg.OpLogDumpMessageProto.Operation.Type.GET;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public mobile.context.msg.OpLogDumpMessageProto.Operation.Type getType() {
        return type_;
      }
      public Builder setType(mobile.context.msg.OpLogDumpMessageProto.Operation.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = mobile.context.msg.OpLogDumpMessageProto.Operation.Type.GET;
        onChanged();
        return this;
      }
      
      // optional bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:mobile.context.msg.Operation)
    }
    
    static {
      defaultInstance = new Operation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mobile.context.msg.Operation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_context_msg_OpLogDumpMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobile_context_msg_OpLogDumpMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_context_msg_OpLogEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobile_context_msg_OpLogEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mobile_context_msg_Operation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mobile_context_msg_Operation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016oplogmsg.proto\022\022mobile.context.msg\"\256\001\n" +
      "\020OpLogDumpMessage\022\021\n\tclient_id\030\001 \001(\t\022,\n\005" +
      "oplog\030\002 \003(\0132\035.mobile.context.msg.Operati" +
      "on\0227\n\004type\030\003 \002(\0162).mobile.context.msg.Op" +
      "LogDumpMessage.Type\" \n\004Type\022\010\n\004DUMP\020\001\022\016\n" +
      "\nDUMP_REPLY\020\002\"\\\n\nOpLogEntry\022\021\n\ttimestamp" +
      "\030\001 \002(\004\022*\n\003ops\030\002 \003(\0132\035.mobile.context.msg" +
      ".Operation\022\017\n\007objname\030\003 \002(\t\"\373\001\n\tOperatio" +
      "n\0225\n\004type\030\001 \002(\0162\".mobile.context.msg.Ope" +
      "ration.Type:\003GET\022\014\n\004data\030\002 \001(\014\"\250\001\n\004Type\022",
      "\007\n\003GET\020\000\022\007\n\003PUT\020\001\022\010\n\004POST\020\002\022\n\n\006DELETE\020\003\022" +
      "\010\n\004MOVE\020\004\022\n\n\006GET_OK\020\005\022\014\n\010GET_FAIL\020\006\022\n\n\006P" +
      "UT_OK\020\007\022\014\n\010PUT_FAIL\020\010\022\013\n\007POST_OK\020\t\022\r\n\tPO" +
      "ST_FAIL\020\n\022\r\n\tDELETE_OK\020\013\022\017\n\013DELETE_FAIL\020" +
      "\014B\027B\025OpLogDumpMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mobile_context_msg_OpLogDumpMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mobile_context_msg_OpLogDumpMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mobile_context_msg_OpLogDumpMessage_descriptor,
              new java.lang.String[] { "ClientId", "Oplog", "Type", },
              mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.class,
              mobile.context.msg.OpLogDumpMessageProto.OpLogDumpMessage.Builder.class);
          internal_static_mobile_context_msg_OpLogEntry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mobile_context_msg_OpLogEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mobile_context_msg_OpLogEntry_descriptor,
              new java.lang.String[] { "Timestamp", "Ops", "Objname", },
              mobile.context.msg.OpLogDumpMessageProto.OpLogEntry.class,
              mobile.context.msg.OpLogDumpMessageProto.OpLogEntry.Builder.class);
          internal_static_mobile_context_msg_Operation_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_mobile_context_msg_Operation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mobile_context_msg_Operation_descriptor,
              new java.lang.String[] { "Type", "Data", },
              mobile.context.msg.OpLogDumpMessageProto.Operation.class,
              mobile.context.msg.OpLogDumpMessageProto.Operation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
